### ISSUE TITLE
Some fields need to be quoted

### ISSUE THREAD

**Issue by pnomolos** [dtgilles/tinyproxy#1]
For example, it's a configuration error if `ViaProxyName` is configured with an unquoted string.  Based on the example configuration file I think the following all need to be quoted, but I didn't test every one.
- ViaProxyName
- Anonymous
- ReverseBaseURL
- StatHost
- AddHeader
- ReversePath

The final two take two arguments, but I almost every case I think it's safe to assume that the first has no spaces in it, so it could be split on that.

I'd take a stab at this, but my bash scripting is very weak so I feel like I'd make a mess of things :(

**Comment by pnomolos** [comment]
Alternatively, I _think_ you could update the documentation to indicate that you need to double-quote those arguments, like so?
- `-ViaProxyName '"tinyproxy"'`

I think the single quotes would be stripped by bash, but the rest passed into `entry.sh` as-is, which might solve the problem.

**Comment by dtgilles** [comment]
@pnomolos: Thanks for creating this issue and your work!
I updated the documentation.
